In [2]:
import math

import numpy as np
import pandas as pd

In [8]:
def map_labels(x):
    if type(x) is str:
        x = x.replace('\u200c', '').replace('.', '')
    if x == 'important' or x == '\'important\'' or x == '1' or x == '\'1\'' or x == '58' or x == 58 or x == '\'58\'' or x == '(1)' or x == '۱':
        return 1
    elif x == 'not important' or x == '\'not important\'' or x == '0' or x == '\'0\'' or x == '47' or x == 47 or x == '\'47\'' or x == '۰':
        return 0
    if math.isnan(x):
        return 0
    x = int(x)
    if x == 0 or x == 1:
        return x
    return 0

In [6]:
result_18 = pd.read_csv('../Datasets/System_Prompt18_Train_Data_Results.csv')
result_19 = pd.read_csv('../Datasets/System_Prompt19_Train_Data_Results.csv')
result_21 = pd.read_csv('../Datasets/System_Prompt21_Train_Data_Results.csv')
result_24 = pd.read_csv('../Datasets/System_Prompt24_Train_Data_Results.csv')
result_25 = pd.read_csv('../Datasets/System_Prompt25_Train_Data_Results.csv')

In [7]:
result_df = pd.DataFrame({
    'text': result_18['text'],
    'text_type': ['only_title'] * len(result_18),
    'real_tag': result_18['real_tag'],
    'category': result_18['category'],
    'prompt18': result_18['predicted_k_0'],
    'prompt19': result_19['predicted_k_0'],
    'prompt21': result_21['predicted_k_0'],
    'prompt24': result_24['predicted_k_0'],
    'prompt25': result_25['predicted_k_0']
})
result_df.head(5)

,text,text_type,real_tag,category,prompt18,prompt19,prompt21,prompt24,prompt25
0,این ورزش سیاسی است!,only_title,0,ورزشی,0.0,0,0.0,0.0,0.0
1,جزئیات نشست غیرعلنی امروز مجلس/آیا اولویت ، مو...,only_title,0,سیاسی,1.0,1,1.0,0.0,1.0
2,کاهش قیمت طلا و سکه در بازار؛ سکه طرح قدیم چند...,only_title,0,اقتصادی,0.0,1,1.0,0.0,0.0
3,عراق غرامت کامل جنگ کویت را پرداخت کرد,only_title,0,اخبار جهان,0.0,0,0.0,0.0,0.0
4,جزئیات توافق ایران و آژانس/پاسخ به دعوت طالبان...,only_title,0,سیاسی,1.0,1,1.0,1.0,0.0

In [12]:
for column in ['prompt18', 'prompt19', 'prompt21', 'prompt24', 'prompt25']:
    result_df[column] = result_df[column].apply(map_labels)
result_df.head(5)

,text,text_type,real_tag,category,prompt18,prompt19,prompt21,prompt24,prompt25
0,این ورزش سیاسی است!,only_title,0,ورزشی,0,0,0,0,0
1,جزئیات نشست غیرعلنی امروز مجلس/آیا اولویت ، مو...,only_title,0,سیاسی,1,1,1,0,1
2,کاهش قیمت طلا و سکه در بازار؛ سکه طرح قدیم چند...,only_title,0,اقتصادی,0,1,1,0,0
3,عراق غرامت کامل جنگ کویت را پرداخت کرد,only_title,0,اخبار جهان,0,0,0,0,0
4,جزئیات توافق ایران و آژانس/پاسخ به دعوت طالبان...,only_title,0,سیاسی,1,1,1,1,0

In [13]:
result_df.to_csv('../Datasets/All_Prompts_Train_Data_Results.csv', index=False)