In [1]:
import math

import numpy as np
import pandas as pd

In [2]:
def map_labels(x):
    if type(x) is str:
        x = x.replace('\u200c', '').replace('.', '')
    if x == 'important' or x == '\'important\'' or x == '1' or x == '\'1\'' or x == '58' or x == 58 or x == '\'58\'' or x == '(1)' or x == '۱':
        return 1
    elif x == 'not important' or x == '\'not important\'' or x == '0' or x == '\'0\'' or x == '47' or x == 47 or x == '\'47\'' or x == '۰':
        return 0
    if math.isnan(x):
        return 0
    x = int(x)
    if x == 0 or x == 1:
        return x
    return 0

In [3]:
result_18 = pd.read_csv('../Datasets/System_Prompt18_Eval_Data_Results.csv')
result_19 = pd.read_csv('../Datasets/System_Prompt19_Eval_Data_Results.csv')
result_21 = pd.read_csv('../Datasets/System_Prompt21_Eval_Data_Results.csv')
result_24 = pd.read_csv('../Datasets/System_Prompt24_Eval_Data_Results.csv')
result_25 = pd.read_csv('../Datasets/System_Prompt25_Eval_Data_Results.csv')

In [4]:
result_df = pd.DataFrame({
    'text': result_18['text'],
    'text_type': ['only_title'] * len(result_18),
    'real_tag': result_18['real_tag'],
    'category': result_18['category'],
    'prompt18': result_18['predicted_k_0'],
    'prompt19': result_19['predicted_k_0'],
    'prompt21': result_21['predicted_k_0'],
    'prompt24': result_24['predicted_k_0'],
    'prompt25': result_25['predicted_k_0']
})
result_df.head(5)

,text,text_type,real_tag,category,prompt18,prompt19,prompt21,prompt24,prompt25
0,4 بازیکن باعث توقف بازی برزیل و آرژانتین شدند/عکس,only_title,1,ورزشی,1.0,0.0,1.0,0.0,0.0
1,نسخه جدید برای جبران کمبود دارویی,only_title,1,اجتماعی,1.0,1.0,1.0,0.0,1.0
2,دیدار ابراهیم رئیسی با رئیس جمهور چین در پکن/ ...,only_title,0,سیاسی,1.0,1.0,1.0,1.0,0.0
3,یک گزارش جدید درباره پاندمی کرونا: مصیبت شمار ...,only_title,0,سلامت و پزشکی,1.0,1.0,1.0,1.0,1.0
4,عملکرد صدا و سیما فرار رو به جلوست/ تلویزیون ب...,only_title,0,فرهنگی و هنری,0.0,0.0,1.0,0.0,1.0

In [5]:
for column in ['prompt18', 'prompt19', 'prompt21', 'prompt24', 'prompt25']:
    result_df[column] = result_df[column].apply(map_labels)
result_df.head(5)

,text,text_type,real_tag,category,prompt18,prompt19,prompt21,prompt24,prompt25
0,4 بازیکن باعث توقف بازی برزیل و آرژانتین شدند/عکس,only_title,1,ورزشی,1,0,1,0,0
1,نسخه جدید برای جبران کمبود دارویی,only_title,1,اجتماعی,1,1,1,0,1
2,دیدار ابراهیم رئیسی با رئیس جمهور چین در پکن/ ...,only_title,0,سیاسی,1,1,1,1,0
3,یک گزارش جدید درباره پاندمی کرونا: مصیبت شمار ...,only_title,0,سلامت و پزشکی,1,1,1,1,1
4,عملکرد صدا و سیما فرار رو به جلوست/ تلویزیون ب...,only_title,0,فرهنگی و هنری,0,0,1,0,1

In [6]:
result_df.to_csv('../Datasets/All_Prompts_Eval_Data_Results.csv', index=False)